server:
  port: 9090
spring:
    datasource:
        initialize: false
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        xa:
            data-source-class-name: org.hsqldb.jdbc.JDBCDataSource
        continue-on-error: true
    jpa:
        database-platform: org.hibernate.dialect.HSQLDialect
        database: HSQL
        show_sql: true
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.event.merge.entity_copy_observer: allow
            hibernate.format_sql: true
            hibernate.use_sql_comments: true

flyway:
  baseline-on-migrate: true
  validate-on-migrate: false
  locations:
    - db/migration
  enabled: true