server:
  port: 9090

spring:
    data:
      mongodb:
        uri:     mongodb://localhost:27017
        database: cars
      elasticsearch:
        cluster-name: elasticsearch
        cluster-nodes: localhost:9300
    datasource:
        initialize: false
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3307/cars
        name: userDB
        username: root
        password: root
        xa:
            data-source-class-name: org.mariadb.jdbc.MySQLDataSource
        test-while-idle: true
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show_sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.event.merge.entity_copy_observer: allow
            hibernate.format_sql: false
            hibernate.use_sql_comments: false
        hibernate:
          ddl-auto: none
    messages:
      basename: i18n/messages
      cache-seconds: 1
      always-use-message-format: true
    thymeleaf:
      cache: false
      mode: XHTML
    mail:
      host:      smtpng.dfinet.ch
      port :     465
      username:  webmaster@agendasante.ch
      password:  wD9DtbmL[zsR
      from :     webmaster@agendasante.ch
      protocol : smtp
      properties:
        mail.smtp.auth:  true
        mail.smtp.ssl.enable : true

    http:
      multipart:
        max-file-size: -1
        max-request-size: -1


flyway:
  baseline-on-migrate: true
  validate-on-migrate: false
  locations:
    - db/migration
  enabled: true



car:
  async:
    enabled: true
    threadPoolSize: 4
  swagger:
    title: Car show application
    description: CAR SHOW API documentation
    version: 0.1.0
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:
  oauth2:
    client_id: mMKBdsIgpC9prxBwgd6V
    client_secret: QzNmrG57pQpt5B9azA01
    grant_type: authorization_code,refresh_token,password,implicit
    scope: read,write
    token_validity: 3600
    refresh_token_validity: 3600
    jwt_key: I8opCRdidwqvG6F7xqGQ
  email:
    from: car@show.fr
    adminEmail : mahjoub.marzougui@olbati.fr
