apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch
  labels: 
    visualize: "true"
    name: elasticsearch
spec:
  replicas: 1
  selector: 
    name: elasticsearch
  template:
    metadata:
      labels:
        visualize: "true"
        app: elasticsearch
        version: "0.0.1"
        uses: elasticsearch
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:2.4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
