apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    visualize: "true"
    app: elasticsearch
    name: elasticsearch
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
  selector:
    name: elasticsearch
