apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels: 
    visualize: "true"
    name: frontend
spec:
  replicas: 1
  selector: 
    name: frontend
  template:
    metadata:
      labels:
        visualize: "true"
        app: frontend
        version: "0.0.1"
        uses: frontend
        name: frontend
    spec:
      containers:
      - name: front
        image: mahjoub/ogt-docker-front
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 5555
        command: [ "npm" ,"start" ]
