apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    visualize: "true"
    app: mariadb
    name: mariadb
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    name: mariadb
