apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb
  labels: 
    visualize: "true"
    name: mariadb
spec:
  replicas: 1
  selector: 
    name: mariadb
  template:
    metadata:
      labels:
        visualize: "true"
        app: mariadb
        version: "0.0.1"
        uses: mariadb
        name: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: cars
        ports:
        - containerPort: 3306
